antivm-obj-y += mouse-rmove.o
antivm-obj-y += key-rhit.o
antivm-obj-y += api_hook.o
antivm-obj-y += pic_button.o
mouse-rmove.o-cflags := -O1
key-rhit.o-cflags := -O1
api_hook.o-cflags := -O1
pic_button.o-cflags := -O0
